// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ME_SharedExp","status":true,"description":"A plugin to manage exp sharing","parameters":{"Mode":"Everyone in party gets the same exp, reserve too"}}
];
